meta_product_name: "The Guild"
meta_title: "The Guild - Connect with the ones closest to you"
meta_description: "The Guild is the new social media in town. The Guild will allow you to stay in touch with your beloveds, organize events, making daily tasks funny for your kids and much more!"
meta_image: "https://res.cloudinary.com/dx6rtf9wl/image/upload/v1615303801/the-guild-ogimage_rthrtl.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards